name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Run Lint
        run: npm run lint
